spring.application.name=FinalProject
spring.datasource.url=jdbc:postgresql://localhost:5432/cinereserve
spring.datasource.username=postgres
spring.datasource.password=shaden

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.docker.compose.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

